# Use the latest CircleCI pipeline process engine version.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  github-cli: circleci/github-cli@2.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  build_image_and_deploy:
    docker:
      - image: docker:17.05.0-ce-git
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: "Create image tag"
          command: |
            set -e
            echo "export image_tag=astro-$(date +%Y%m%d%H%M%S)" >> $BASH_ENV
            source "$BASH_ENV"
            printenv
      - run:
          name: "Build Docker image"
          command: |
            docker build -t ${image_tag} .
      - run:
          name: "Deploy to Astro"
          command: |
            curl -sSL install.astronomer.io | sudo bash -s
            astro deploy --image-name ${image-tag} ${ASTRO_DEPLOYMENT_ID} -f

# Invoke jobs with workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2.1
  build-and-deploy-prod:
    jobs:
      - build_image_and_deploy:
          context:
            - dev-airflow
