name: Astronomer CI - Additional build-time args

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_SECRET_ID }}
      DEV_DEPLOYMENT_ID: ${{ secrets.DEV_DEPLOYMENT_ID }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Create image tag
      id: image_tag
      run: echo ::set-output name=image_tag::astro-$(date +%Y%m%d%H%M%S)
    - name: Build image
      uses: docker/build-push-action@v4
      with:
        tags: ${{ steps.image_tag.outputs.image_tag }}
        load: true
        # Define your custom image's build arguments, contexts, and connections here using
        # the available GitHub Action settings:
        # https://github.com/docker/build-push-action#customizing .
        # This example uses `build-args` , but your use case might require configuring
        # different values.
    - name: Deploy to Astro
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy ${{ env.DEV_DEPLOYMENT_ID }} --image-name ${{ steps.image_tag.outputs.image_tag }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # ENV VARs ############################################################################################
#     env:
#       ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
#     steps:
#     - name: Set mk environment variables
#       run: |
#         echo "DEPLOYMENT_ID=${{ secrets.MK_DEPLOYMENT_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_ID=${{ secrets.MK_ASTRONOMER_KEY_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_SECRET=${{ secrets.MK_ASTRONOMER_KEY_SECRET }}" >> $GITHUB_ENV
#       if: github.ref == 'refs/heads/mk_dev'
#     - name: Set dev environment variables
#       run: |
#         echo "DEPLOYMENT_ID=${{ secrets.DEV_DEPLOYMENT_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_ID=${{ secrets.DEV_ASTRONOMER_KEY_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_SECRET=${{ secrets.DEV_ASTRONOMER_KEY_SECRET }}" >> $GITHUB_ENV
#       if: github.ref == 'refs/heads/dev'
#     - name: Set stage environment variables
#       run: |
#         echo "DEPLOYMENT_ID=${{ secrets.STAGE_DEPLOYMENT_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_ID=${{ secrets.STAGE_ASTRONOMER_KEY_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_SECRET=${{ secrets.STAGE_ASTRONOMER_KEY_SECRET }}" >> $GITHUB_ENV
#       if: github.ref == 'refs/heads/stage'
#     - name: Set stage environment variables
#       run: |
#         echo "DEPLOYMENT_ID=${{ secrets.MAIN_DEPLOYMENT_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_ID=${{ secrets.MAIN_ASTRONOMER_KEY_ID }}" >> $GITHUB_ENV
#         echo "ASTRONOMER_KEY_SECRET=${{ secrets.MAIN_ASTRONOMER_KEY_SECRET }}" >> $GITHUB_ENV
#       if: github.ref == 'refs/heads/main'
#     # ENV VARs ############################################################################################
#     - name: Checkout our Repo.
#       uses: actions/checkout@v3
#     - name: Install the Astro CLI.
#       run: brew install astronomer/cloud/astrocloud@1.3.2
#     - name: Deploying the image to Astro.
#       run: 
#         astrocloud deploy ${{ env.DEPLOYMENT_ID }}
